### ISSUE TITLE
how to use Redis Geo with php?

### ISSUE THREAD

**Issue by JoyCood** [mattsta/redis#6]
Hi, mattsta, could you tell me how to use Redis Geo with php-redis extension module?

**Comment by mattsta** [comment]
There's two ways:
  - If you compile php-redis in debug mode, it provides a special function to run _any_ command instead of only the built-in allowed commands.
  - Or, you can wrap any commands not allowed by your client in a Lua script.  Basically, a very short `EVAL 'return redis.call('georadius', a, b, c, ...);' ...`
